[package]
name = "dhcp_parser"
version = "0.1.0"
authors = ["Paul Woolcock <paul@woolcock.us>"]

[dependencies]
nom = "*"

[dependencies.enum_primitive]
git = "https://github.com/pwoolcoc/enum_primitive-rs"

[dependencies.num]
version = "*"
default-features = false

